
project_id = "tekpogcmgdfdbgnzivvi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[functions]
[functions.chatbot]
verify_jwt = false

[functions.ai-product-generator]
verify_jwt = false
