
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tekpogcmgdfdbgnzivvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRla3BvZ2NtZ2RmZGJnbnppdnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NzMzODEsImV4cCI6MjA1NzM0OTM4MX0.g0y2ZYF5PUjJUCxJ_0W8VbHyGiROfEblIjyedjScqN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true
    }
  }
);

// Enable realtime subscriptions for relevant tables
const enableRealtimeForTables = async () => {
  try {
    // Enable for products table
    await supabase.channel('table-db-changes')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'products'
      }, (payload) => console.log('Product change received:', payload))
      .subscribe();
      
    // Enable for orders table
    await supabase.channel('orders-db-changes')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'orders'
      }, (payload) => console.log('Order change received:', payload))
      .subscribe();
      
    // Enable for order_items table
    await supabase.channel('order-items-db-changes')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'order_items'
      }, (payload) => console.log('Order item change received:', payload))
      .subscribe();
      
    console.log('Realtime subscriptions enabled for tables');
  } catch (error) {
    console.error('Error enabling realtime subscriptions:', error);
  }
};

// Initialize realtime subscriptions
enableRealtimeForTables();
