
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tekpogcmgdfdbgnzivvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRla3BvZ2NtZ2RmZGJnbnppdnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NzMzODEsImV4cCI6MjA1NzM0OTM4MX0.g0y2ZYF5PUjJUCxJ_0W8VbHyGiROfEblIjyedjScqN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true
    }
  }
);

// Maps frontend role to database role
export const mapRoleToDatabase = (frontendRole: string): string => {
  const roleMap: Record<string, string> = {
    'super_admin': 'admin',
    'manager': 'moderator',
    'support': 'user'
  };
  return roleMap[frontendRole] || 'user';
};

// Check if the current user has a specific database role
export const checkUserDatabaseRole = async (databaseRole: string): Promise<boolean> => {
  try {
    // Get current user
    const { data: { user } } = await supabase.auth.getUser();
    
    if (!user) return false;
    
    // Call the has_role RPC with both required parameters
    const { data, error } = await supabase.rpc('has_role', { 
      _user_id: user.id,
      _role: databaseRole as "admin" | "moderator" | "user"
    });
    
    if (error) throw error;
    return !!data;
  } catch (error) {
    console.error('Error checking user role:', error);
    return false;
  }
};

// Enable realtime subscriptions for relevant tables
const enableRealtimeForTables = async () => {
  try {
    // Enable for products table
    await supabase.channel('table-db-changes')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'products'
      }, (payload) => console.log('Product change received:', payload))
      .subscribe();
      
    // Enable for orders table
    await supabase.channel('orders-db-changes')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'orders'
      }, (payload) => console.log('Order change received:', payload))
      .subscribe();
      
    // Enable for order_items table
    await supabase.channel('order-items-db-changes')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'order_items'
      }, (payload) => console.log('Order item change received:', payload))
      .subscribe();
      
    // Enable for abandoned_cart_notifications table
    await supabase.channel('abandoned-cart-notifications-changes')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'abandoned_cart_notifications'
      }, (payload) => console.log('Abandoned cart notification change received:', payload))
      .subscribe();
      
    // Enable for carts table
    await supabase.channel('carts-changes')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'carts'
      }, (payload) => console.log('Cart change received:', payload))
      .subscribe();
      
    // Enable for product_collections table
    await supabase.channel('product-collections-changes')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'product_collections'
      }, (payload) => console.log('Product collection change received:', payload))
      .subscribe();
      
    console.log('Realtime subscriptions enabled for tables');
  } catch (error) {
    console.error('Error enabling realtime subscriptions:', error);
  }
};

// Initialize realtime subscriptions
enableRealtimeForTables();
